In [1]:
import pandas as pd
import numpy as np
import requests
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.decomposition import TruncatedSVD, NMF

/Users/romi9987/Documents/Python_Workspace/llm-course/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [2]:
# Download the data:

docs_url = 'https://github.com/alexeygrigorev/llm-rag-workshop/raw/main/notebooks/documents.json'
docs_response = requests.get(docs_url)
documents_raw = docs_response.json()

documents = []

for course in documents_raw:
    course_name = course['course']

    for doc in course['documents']:
        doc['course'] = course_name
        documents.append(doc)

In [3]:
documents[2]

{'text': "Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute.",
 'section': 'General course-related questions',
 'question': 'Course - Can I still join the course after the start date?',
 'course': 'data-engineering-zoomcamp'}

In [4]:
df = pd.DataFrame(documents)

In [5]:
df.head()

,text,section,question,course
0,The purpose of this document is to capture fre...,General course-related questions,Course - When will the course start?,data-engineering-zoomcamp
1,GitHub - DataTalksClub data-engineering-zoomca...,General course-related questions,Course - What are the prerequisites for this c...,data-engineering-zoomcamp
2,"Yes, even if you don't register, you're still ...",General course-related questions,Course - Can I still join the course after the...,data-engineering-zoomcamp
3,You don't need it. You're accepted. You can al...,General course-related questions,Course - I have registered for the Data Engine...,data-engineering-zoomcamp
4,You can start by installing and setting up all...,General course-related questions,Course - What can I do before the course starts?,data-engineering-zoomcamp

In [6]:
df = pd.DataFrame(documents, columns=['course', 'section', 'question', 'text'])
df.head()

,course,section,question,text
0,data-engineering-zoomcamp,General course-related questions,Course - When will the course start?,The purpose of this document is to capture fre...
1,data-engineering-zoomcamp,General course-related questions,Course - What are the prerequisites for this c...,GitHub - DataTalksClub data-engineering-zoomca...
2,data-engineering-zoomcamp,General course-related questions,Course - Can I still join the course after the...,"Yes, even if you don't register, you're still ..."
3,data-engineering-zoomcamp,General course-related questions,Course - I have registered for the Data Engine...,You don't need it. You're accepted. You can al...
4,data-engineering-zoomcamp,General course-related questions,Course - What can I do before the course starts?,You can start by installing and setting up all...

In [7]:
# Basics of Text Search

# Information Retrieval - The process of obtaining relevant information from large datasets based on user queries.

# Vector Spaces - A mathematical representation where text is converted into vectors 
# (points in space) allowing for quantitative comparison.

# Bag of Words - A simple text representation model treating each document as a collection of words
# disregarding grammar and word order but keeping multiplicity.

# TF-IDF (Term Frequency-Inverse Document Frequency) - A statistical measure used to evaluate how important a word
# is to a document in a collection or corpus. 
# It increases with the number of times a word appears in the document 
# but is offset by the frequency of the word in the corpus.

cv = CountVectorizer(min_df=5) # min document frequency

In [8]:
cv.fit(df.text)

CountVectorizer(min_df=5)

In [9]:
cv.get_feature_names_out().shape

(1524,)

In [10]:
cv.get_feature_names_out()

array(['01', '02', '03', ..., 'youtube', 'zip', 'zoomcamp'], dtype=object)

In [11]:
#Bag of words - we don't care about word order, we just care about the presence of words
# we use sparse matrix

# For Count Vectorizer and TF-IDF we will first use a simple example

docs_example = [
    "Course starts on 15th Jan 2024",
    "Prerequisites listed on GitHub",
    "Submit homeworks after start date",
    "Registration not required for participation",
    "Setup Google Cloud and Python before course"
]

In [12]:
cv = CountVectorizer(stop_words='english')

In [13]:
cv.fit(docs_example)

CountVectorizer(stop_words='english')

In [14]:
cv.get_feature_names_out()

array(['15th', '2024', 'cloud', 'course', 'date', 'github', 'google',
       'homeworks', 'jan', 'listed', 'participation', 'prerequisites',
       'python', 'registration', 'required', 'setup', 'start', 'starts',
       'submit'], dtype=object)

In [15]:
X = cv.transform(docs_example)

In [16]:
X.todense()

matrix([[1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0],
        [0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0]])

In [17]:
pd.DataFrame(X.todense(), columns=cv.get_feature_names_out())

,15th,2024,cloud,course,date,github,google,homeworks,jan,listed,participation,prerequisites,python,registration,required,setup,start,starts,submit
0,1,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,1
3,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0
4,0,0,1,1,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0

In [18]:
pd.DataFrame(X.todense(), columns=cv.get_feature_names_out()).T

               0  1  2  3  4
15th           1  0  0  0  0
2024           1  0  0  0  0
cloud          0  0  0  0  1
course         1  0  0  0  1
date           0  0  1  0  0
github         0  1  0  0  0
google         0  0  0  0  1
homeworks      0  0  1  0  0
jan            1  0  0  0  0
listed         0  1  0  0  0
participation  0  0  0  1  0
prerequisites  0  1  0  0  0
python         0  0  0  0  1
registration   0  0  0  1  0
required       0  0  0  1  0
setup          0  0  0  0  1
start          0  0  1  0  0
starts         1  0  0  0  0
submit         0  0  1  0  0

In [20]:
cv = CountVectorizer(stop_words='english', min_df=5)
X = cv.fit_transform(df.text)

names = cv.get_feature_names_out()

df_docs = pd.DataFrame(X.toarray(), columns=names).T
df_docs

,0,1,2,3,4,5,6,7,8,9,...,938,939,940,941,942,943,944,945,946,947
01,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
02,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
03,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
04,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
05,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
yes,0,0,1,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
yml,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
youtube,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
zip,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
zoomcamp,0,1,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [21]:
# with TFIDF the more important the word is, the higher weight of this word

tf = TfidfVectorizer(stop_words='english', min_df=5)
X = tf.fit_transform(df.text)

names = tf.get_feature_names_out()

df_docs = pd.DataFrame(X.toarray(), columns=names)
df_docs.round(2)

,01,02,03,04,05,06,09,10,100,11,...,y_val,yaml,year,yellow,yellow_tripdata_2021,yes,yml,youtube,zip,zoomcamp
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.00
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.43
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.0,0.0,0.0,0.28,0.00,0.0,0.0,0.00
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.00
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.0,0.0,0.0,0.00,0.11,0.0,0.0,0.00
944,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.00
945,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.17,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.00
946,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.00
947,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.15

In [22]:
query = "I just discovered the course, is it too late to join?"

q = tf.transform([query])
q.toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [23]:
query_dict = dict(zip(names, q.toarray()[0]))
query_dict

{'01': 0.0,
 '02': 0.0,
 '03': 0.0,
 '04': 0.0,
 '05': 0.0,
 '06': 0.0,
 '09': 0.0,
 '10': 0.0,
 '100': 0.0,
 '11': 0.0,
 '12': 0.0,
 '127': 0.0,
 '13': 0.0,
 '14': 0.0,
 '15': 0.0,
 '16': 0.0,
 '17': 0.0,
 '19': 0.0,
 '1st': 0.0,
 '20': 0.0,
 '2019': 0.0,
 '2020': 0.0,
 '2021': 0.0,
 '2022': 0.0,
 '2023': 0.0,
 '2024': 0.0,
 '21': 0.0,
 '22': 0.0,
 '24': 0.0,
 '25': 0.0,
 '2pacx': 0.0,
 '30': 0.0,
 '35': 0.0,
 '403': 0.0,
 '42': 0.0,
 '50': 0.0,
 '5000': 0.0,
 '5431': 0.0,
 '5432': 0.0,
 '60': 0.0,
 '600': 0.0,
 '7077': 0.0,
 '80': 0.0,
 '8080': 0.0,
 '8888': 0.0,
 '9696': 0.0,
 'abhijit': 0.0,
 'able': 0.0,
 'abolade': 0.0,
 'absolute': 0.0,
 'accept': 0.0,
 'access': 0.0,
 'accordingly': 0.0,
 'account': 0.0,
 'accuracy': 0.0,
 'action': 0.0,
 'activate': 0.0,
 'actual': 0.0,
 'actually': 0.0,
 'add': 0.0,
 'added': 0.0,
 'adding': 0.0,
 'addition': 0.0,
 'additional': 0.0,
 'additionally': 0.0,
 'address': 0.0,
 'admin': 0.0,
 'advani': 0.0,
 'ahmed': 0.0,
 'ai': 0.0,
 'airflow': 0.0,
 'alejandro': 0.0,
 'alena': 0.0,
 'alex': 0.0,
 'alexey': 0.0,
 'alexeygrigorev': 0.0,
 'allocate': 0.0,
 'allow': 0.0,
 'allowed': 0.0,
 'allowing': 0.0,
 'allows': 0.0,
 'alpha': 0.0,
 'alternative': 0.0,
 'alternatively': 0.0,
 'amazon': 0.0,
 'amazonaws': 0.0,
 'amd64': 0.0,
 'aminat': 0.0,
 'anaconda': 0.0,
 'anaconda3': 0.0,
 'analytics': 0.0,
 'anand': 0.0,
 'andrii': 0.0,
 'ans': 0.0,
 'answer': 0.0,
 'answered': 0.0,
 'answers': 0.0,
 'apache': 0.0,
 'api': 0.0,
 'aponte': 0.0,
 'app': 0.0,
 'appear': 0.0,
 'appears': 0.0,
 'append': 0.0,
 'application': 0.0,
 'apply': 0.0,
 'appname': 0.0,
 'approach': 0.0,
 'apt': 0.0,
 'architecture': 0.0,
 'archives': 0.0,
 'args': 0.0,
 'argument': 0.0,
 'array': 0.0,
 'arrays': 0.0,
 'article': 0.0,
 'asia': 0.0,
 'ask': 0.0,
 'asked': 0.0,
 'asks': 0.0,
 'assigned': 0.0,
 'astype': 0.0,
 'attempting': 0.0,
 'attribute': 0.0,
 'attributeerror': 0.0,
 'auc': 0.0,
 'auth': 0.0,
 'authenticate': 0.0,
 'authentication': 0.0,
 'auto': 0.0,
 'automatically': 0.0,
 'available': 0.0,
 'average': 0.0,
 'avila': 0.0,
 'avoid': 0.0,
 'aws': 0.0,
 'azure': 0.0,
 'backend': 0.0,
 'bad': 0.0,
 'bar': 0.0,
 'base': 0.0,
 'based': 0.0,
 'bash': 0.0,
 'bashrc': 0.0,
 'basically': 0.0,
 'batch': 0.0,
 'best': 0.0,
 'better': 0.0,
 'bhaskar': 0.0,
 'bhatia': 0.0,
 'big': 0.0,
 'bigquery': 0.0,
 'billing': 0.0,
 'bin': 0.0,
 'binary': 0.0,
 'bind': 0.0,
 'bit': 0.0,
 'blob': 0.0,
 'block': 0.0,
 'blog': 0.0,
 'box': 0.0,
 'bq': 0.0,
 'branch': 0.0,
 'brew': 0.0,
 'brigida': 0.0,
 'browser': 0.0,
 'bucket': 0.0,
 'build': 0.0,
 'builder': 0.0,
 'building': 0.0,
 'built': 0.0,
 'calculate': 0.0,
 'calderin': 0.0,
 'called': 0.0,
 'calling': 0.0,
 'capstone': 0.0,
 'capture': 0.0,
 'care': 0.0,
 'careful': 0.0,
 'case': 0.0,
 'cast': 0.0,
 'cat': 0.0,
 'categorical': 0.0,
 'cause': 0.0,
 'caused': 0.0,
 'causing': 0.0,
 'cd': 0.0,
 'cell': 0.0,
 'certificate': 0.0,
 'chakraborty': 0.0,
 'change': 0.0,
 'changed': 0.0,
 'changes': 0.0,
 'changing': 0.0,
 'channel': 0.0,
 'check': 0.0,
 'checking': 0.0,
 'chizhmak': 0.0,
 'chmod': 0.0,
 'choice': 0.0,
 'choose': 0.0,
 'chown': 0.0,
 'churn': 0.0,
 'ci': 0.0,
 'class': 0.0,
 'classes': 0.0,
 'classification': 0.0,
 'clear': 0.0,
 'cli': 0.0,
 'click': 0.0,
 'client': 0.0,
 'clone': 0.0,
 'close': 0.0,
 'closed': 0.0,
 'closest': 0.0,
 'clothing': 0.0,
 'cloud': 0.0,
 'cloudfront': 0.0,
 'club': 0.0,
 'cluster': 0.0,
 'cmd': 0.0,
 'code': 0.0,
 'codespaces': 0.0,
 'coding': 0.0,
 'cohort': 0.0,
 'cohorts': 0.0,
 'col': 0.0,
 'colab': 0.0,
 'column': 0.0,
 'columns': 0.0,
 'com': 0.0,
 'command': 0.0,
 'commands': 0.0,
 'commit': 0.0,
 'common': 0.0,
 'community': 0.0,
 'compatibility': 0.0,
 'compatible': 0.0,
 'complete': 0.0,
 'completed': 0.0,
 'compose': 0.0,
 'compute': 0.0,
 'computer': 0.0,
 'conda': 0.0,
 'config': 0.0,
 'configuration': 0.0,
 'configure': 0.0,
 'configured': 0.0,
 'confirm': 0.0,
 'connect': 0.0,
 'connecting': 0.0,
 'connection': 0.0,
 'connector': 0.0,
 'consider': 0.0,
 'consistent': 0.0,
 'console': 0.0,
 'contain': 0.0,
 'container': 0.0,
 'containers': 0.0,
 'contains': 0.0,
 'content': 0.0,
 'contents': 0.0,
 'context': 0.0,
 'continue': 0.0,
 'control': 0.0,
 'convert': 0.0,
 'converted': 0.0,
 'copy': 0.0,
 'core': 0.0,
 'correct': 0.0,
 'correctly': 0.0,
 'correlation': 0.0,
 'corresponding': 0.0,
 'couldn': 0.0,
 'course': 0.49695797492447685,
 'cp': 0.0,
 'cpu': 0.0,
 'create': 0.0,
 'create_engine': 0.0,
 'created': 0.0,
 'creates': 0.0,
 'creating': 0.0,
 'creation': 0.0,
 'credentials': 0.0,
 'credit': 0.0,
 'crucial': 0.0,
 'csv': 0.0,
 'ctrl': 0.0,
 'curl': 0.0,
 'current': 0.0,
 'custom': 0.0,
 'd37ci6vzurychx': 0.0,
 'daemon': 0.0,
 'daniel': 0.0,
 'dashboard': 0.0,
 'data': 0.0,
 'database': 0.0,
 'dataframe': 0.0,
 'dataframes': 0.0,
 'dataproc': 0.0,
 'dataset': 0.0,
 'datasets': 0.0,
 'datatalks': 0.0,
 'datatalksclub': 0.0,
 'datatype': 0.0,
 'date': 0.0,
 'datetime': 0.0,
 'david': 0.0,
 'day': 0.0,
 'db': 0.0,
 'dbt': 0.0,
 'dbt_project': 0.0,
 'deadline': 0.0,
 'dealing': 0.0,
 'debian': 0.0,
 'debug': 0.0,
 'deep': 0.0,
 'def': 0.0,
 'default': 0.0,
 'define': 0.0,
 'defined': 0.0,
 'definition': 0.0,
 'delete': 0.0,
 'deleted': 0.0,
 'deleting': 0.0,
 'denied': 0.0,
 'dependencies': 0.0,
 'dependency': 0.0,
 'deploy': 0.0,
 'deploying': 0.0,
 'deployment': 0.0,
 'deprecated': 0.0,
 'description': 0.0,
 'desktop': 0.0,
 'detailed': 0.0,
 'details': 0.0,
 'dev': 0.0,
 'development': 0.0,
 'deviation': 0.0,
 'device': 0.0,
 'df': 0.0,
 'df_train': 0.0,
 'dict': 0.0,
 'dictionary': 0.0,
 'dictvectorizer': 0.0,
 'did': 0.0,
 'didn': 0.0,
 'difference': 0.0,
 'different': 0.0,
 'dino': 0.0,
 'dir': 0.0,
 'directly': 0.0,
 'directory': 0.0,
 'disk': 0.0,
 'distribution': 0.0,
 'doc': 0.0,
 'docker': 0.0,
 'dockerfile': 0.0,
 'docs': 0.0,
 'document': 0.0,
 'documentation': 0.0,
 'does': 0.0,
 'doesn': 0.0,
 'doing': 0.0,
 'dolocationid': 0.0,
 'don': 0.0,
 'dot': 0.0,
 'double': 0.0,
 'downgrade': 0.0,
 'download': 0.0,
 'downloaded': 0.0,
 'downloading': 0.0,
 'downloads': 0.0,
 'dpage': 0.0,
 'dragon': 0.0,
 'drive': 0.0,
 'drop': 0.0,
 'dropoff_datetime': 0.0,
 'dropping': 0.0,
 'dt': 0.0,
 'dtc': 0.0,
 'duration': 0.0,
 'dv': 0.0,
 'easier': 0.0,
 'easiest': 0.0,
 'easily': 0.0,
 'ec2': 0.0,
 'echo': 0.0,
 'ecr': 0.0,
 'edit': 0.0,
 'editing': 0.0,
 'editor': 0.0,
 'email': 0.0,
 'en': 0.0,
 'enable': 0.0,
 'enabled': 0.0,
 'encode': 0.0,
 'encoding': 0.0,
 'encounter': 0.0,
 'encountered': 0.0,
 'end': 0.0,
 'endpoint': 0.0,
 'engine': 0.0,
 'engineering': 0.0,
 'ensure': 0.0,
 'enter': 0.0,
 'entire': 0.0,
 'entries': 0.0,
 'env': 0.0,
 'environ': 0.0,
 'environment': 0.0,
 'environments': 0.0,
 'equal': 0.0,
 'erick': 0.0,
 'error': 0.0,
 'errors': 0.0,
 'escape': 0.0,
 'especially': 0.0,
 'eu': 0.0,
 'europe': 0.0,
 'evaluate': 0.0,
 'evaluated': 0.0,
 'evaluation': 0.0,
 'exactly': 0.0,
 'example': 0.0,
 'exception': 0.0,
 'exe': 0.0,
 'exec': 0.0,
 'executable': 0.0,
 'execute': 0.0,
 'executed': 0.0,
 'executing': 0.0,
 'execution': 0.0,
 'exist': 0.0,
 'existing': 0.0,
 'exists': 0.0,
 'exit': 0.0,
 'expected': 0.0,
 'experiment': 0.0,
 'explanation': 0.0,
 'explicitly': 0.0,
 'export': 0.0,
 'extension': 0.0,
 'external': 0.0,
 'extra': 0.0,
 'extract': 0.0,
 'face': 0.0,
 'faced': 0.0,
 'fact': 0.0,
 'fact_trips': 0.0,
 'fail': 0.0,
 'failed': 0.0,
 'failing': 0.0,
 'fails': 0.0,
 'false': 0.0,
 'faq': 0.0,
 'fatal': 0.0,
 'feature': 0.0,
 'features': 0.0,
 'fetch': 0.0,
 'fhv': 0.0,
 'fhv_tripdata_2019': 0.0,
 'field': 0.0,
 'figure': 0.0,
 'file': 0.0,
 'files': 0.0,
 'filesystem': 0.0,
 'filter': 0.0,
 'final': 0.0,
 'finally': 0.0,
 'findspark': 0.0,
 'fine': 0.0,
 'fit': 0.0,
 'fix': 0.0,
 'fixed': 0.0,
 'flag': 0.0,
 'flask': 0.0,
 'float': 0.0,
 'float64': 0.0,
 'flow': 0.0,
 'folder': 0.0,
 'folders': 0.0,
 'follow': 0.0,
 'followed': 0.0,
 'following': 0.0,
 'follows': 0.0,
 'forbidden': 0.0,
 'force': 0.0,
 'forget': 0.0,
 'forgot': 0.0,
 'form': 0.0,
 'format': 0.0,
 'forms': 0.0,
 'forward': 0.0,
 'fouesnard': 0.0,
 'free': 0.0,
 'fresh': 0.0,
 'fs': 0.0,
 'function': 0.0,
 'functions': 0.0,
 'future': 0.0,
 'gateway': 0.0,
 'gcloud': 0.0,
 'gcp': 0.0,
 'gcs': 0.0,
 'generate': 0.0,
 'generated': 0.0,
 'generator': 0.0,
 'george': 0.0,
 'get_dummies': 0.0,
 'get_feature_names_out': 0.0,
 'getdbt': 0.0,
 'getorcreate': 0.0,
 'gets': 0.0,
 'getting': 0.0,
 'git': 0.0,
 'github': 0.0,
 'githubusercontent': 0.0,
 'gitignore': 0.0,
 'given': 0.0,
 'gives': 0.0,
 'gmail': 0.0,
 'going': 0.0,
 'good': 0.0,
 'google': 0.0,
 'google_application_credentials': 0.0,
 'googleapi': 0.0,
 'googleapis': 0.0,
 'got': 0.0,
 'gpu': 0.0,
 'great': 0.0,
 'green': 0.0,
 'grigorev': 0.0,
 'group': 0.0,
 'gs': 0.0,
 'guide': 0.0,
 'gunicorn': 0.0,
 'gz': 0.0,
 'gzip': 0.0,
 'hadoop': 0.0,
 'hadoop3': 0.0,
 'hand': 0.0,
 'handle': 0.0,
 'happen': 0.0,
 'happens': 0.0,
 'haven': 0.0,
 'having': 0.0,
 'head': 0.0,
 'help': 0.0,
 'helped': 0.0,
 'helps': 0.0,
 'high': 0.0,
 'higher': 0.0,
 'highly': 0.0,
 'home': 0.0,
 'homebrew': 0.0,
 'homework': 0.0,
 'homeworks': 0.0,
 'hope': 0.0,
 'host': 0.0,
 'hostname': 0.0,
 'hot': 0.0,
 'hours': 0.0,
 'housing': 0.0,
 'hrithik': 0.0,
 'html': 0.0,
 'http': 0.0,
 'https': 0.0,
 'humberto': 0.0,
 'hw': 0.0,
 'hws': 0.0,
 'iam': 0.0,
 'icon': 0.0,
 'id': 0.0,
 'ide': 0.0,
 'idea': 0.0,
 'ignore': 0.0,
 'image': 0.0,
 'images': 0.0,
 'immediately': 0.0,
 'import': 0.0,
 'importance': 0.0,
 'important': 0.0,
 'importerror': 0.0,
 'importing': 0.0,
 'include': 0.0,
 'included': 0.0,
 'including': 0.0,
 'increase': 0.0,
 'index': 0.0,
 'info': 0.0,
 'information': 0.0,
 'init': 0.0,
 'initial': 0.0,
 'input': 0.0,
 'inside': 0.0,
 'install': 0.0,
 'installation': 0.0,
 'installed': 0.0,
 'installing': 0.0,
 'instance': 0.0,
 'instances': 0.0,
 'instead': 0.0,
 'instruction': 0.0,
 'instructions': 0.0,
 'insufficient': 0.0,
 'int': 0.0,
 'int64': 0.0,
 'integer': 0.0,
 'interesting': 0.0,
 'interface': 0.0,
 'internal': 0.0,
 'internet': 0.0,
 'interpreter': 0.0,
 'intro': 0.0,
 'invalid': 0.0,
 'io': 0.0,
 'ip': 0.0,
 'ipynb': 0.0,
 'isn': 0.0,
 'issue': 0.0,
 'issues': 0.0,
 'iteration': 0.0,
 'ivan': 0.0,
 'jan': 0.0,
 'jar': 0.0,
 'java': 0.0,
 'java_home': 0.0,
 'job': 0.0,
 'jobs': 0.0,
 'join': 0.7433502942325737,
 'json': 0.0,
 'jupyter': 0.0,
 'just': 0.4477310702009737,
 'kafka': 0.0,
 'kaggle': 0.0,
 'keras': 0.0,
 'kernel': 0.0,
 'key': 0.0,
 'keys': 0.0,
 'kill': 0.0,
 'kind': 0.0,
 'kinesis': 0.0,
 'kniazeva': 0.0,
 'know': 0.0,
 'known': 0.0,
 'konrad': 0.0,
 'krishna': 0.0,
 'kubectl': 0.0,
 'kubernetes': 0.0,
 'kumar': 0.0,
 'kwargs': 0.0,
 'lambda': 0.0,
 'laptop': 0.0,
 'large': 0.0,
 'larkin': 0.0,
 'later': 0.0,
 'latest': 0.0,
 'launch': 0.0,
 'layer': 0.0,
 'layers': 0.0,
 'lead': 0.0,
 'leaderboard': 0.0,
 'learn': 0.0,
 'learning': 0.0,
 'left': 0.0,
 'length': 0.0,
 'lesson': 0.0,
 'lessons': 0.0,
 'let': 0.0,
 'level': 0.0,
 'lib': 0.0,
 'libraries': 0.0,
 'library': 0.0,
 'like': 0.0,
 'likely': 0.0,
 'line': 0.0,
 'linear': 0.0,
 'lines': 0.0,
 'link': 0.0,
 'links': 0.0,
 'linux': 0.0,
 'list': 0.0,
 'listed': 0.0,
 'litvinov': 0.0,
 'live': 0.0,
 'll': 0.0,
 'load': 0.0,
 'loaded': 0.0,
 'loading': 0.0,
 'local': 0.0,
 'localhost': 0.0,
 'locally': 0.0,
 'located': 0.0,
 'location': 0.0,
 'locations': 0.0,
 'lock': 0.0,
 'log': 0.0,
 'logged': 0.0,
 'login': 0.0,
 'logistic': 0.0,
 'logs': 0.0,
 'long': 0.0,
 'longer': 0.0,
 'look': 0.0,
 'looking': 0.0,
 'looks': 0.0,
 'loop': 0.0,
 'lot': 0.0,
 'lower': 0.0,
 'ls': 0.0,
 'lukafiardi': 0.0,
 'mac': 0.0,
 'machine': 0.0,
 'macos': 0.0,
 'mage': 0.0,
 'magic': 0.0,
 'main': 0.0,
 'make': 0.0,
 'makes': 0.0,
 'making': 0.0,
 'manage': 0.0,
 'manually': 0.0,
 'map': 0.0,
 'marcos': 0.0,
 'marcosmjd': 0.0,
 'martin': 0.0,
 'master': 0.0,
 'match': 0.0,
 'matplotlib': 0.0,
 'matrix': 0.0,
 'max': 0.0,
 'maybe': 0.0,
 'md': 0.0,
 'mean': 0.0,
 'mean_squared_error': 0.0,
 'means': 0.0,
 'media': 0.0,
 'median_house_value': 0.0,
 'memoona': 0.0,
 'memory': 0.0,
 'mentioned': 0.0,
 'merge': 0.0,
 'message': 0.0,
 'metadata': 0.0,
 'method': 0.0,
 'metrics': 0.0,
 'microsoft': 0.0,
 'midterm': 0.0,
 'minutes': 0.0,
 'missing': 0.0,
 'mkdir': 0.0,
 'ml': 0.0,
 'mlbookcamp': 0.0,
 'mlflow': 0.0,
 'mlops': 0.0,
 'mode': 0.0,
 'model': 0.0,
 'models': 0.0,
 'modified': 0.0,
 'modify': 0.0,
 'module': 0.0,
 'modulenotfounderror': 0.0,
 'modules': 0.0,
 'month': 0.0,
 'mount': 0.0,
 'moved': 0.0,
 'multiple': 0.0,
 'multiplication': 0.0,
 'mélanie': 0.0,
 'named': 0.0,
 'names': 0.0,
 'nan': 0.0,
 'nano': 0.0,
 'native': 0.0,
 'navigate': 0.0,
 'ndarray': 0.0,
 'necessary': 0.0,
 'need': 0.0,
 'needed': 0.0,
 'needs': 0.0,
 'negative': 0.0,
 'net': 0.0,
 'network': 0.0,
 'networks': 0.0,
 'new': 0.0,
 'newly': 0.0,
 'non': 0.0,
 'normal': 0.0,
 'note': 0.0,
 'notebook': 0.0,
 'notebooks': 0.0,
 'notes': 0.0,
 'notice': 0.0,
 'np': 0.0,
 'nukta': 0.0,
 'null': 0.0,
 'number': 0.0,
 'numeric': 0.0,
 'numerical': 0.0,
 'numpy': 0.0,
 'ny': 0.0,
 'ny_taxi': 0.0,
 'ny_taxi_postgres_data': 0.0,
 'nyc': 0.0,
 'object': 0.0,
 'observations': 0.0,
 'occur': 0.0,
 'occurred': 0.0,
 'occurs': 0.0,
 'odimegwu': 0.0,
 'office': 0.0,
 'official': 0.0,
 'ok': 0.0,
 'old': 0.0,
 'older': 0.0,
 'olga': 0.0,
 'onehotencoder': 0.0,
 'ones': 0.0,
 'open': 0.0,
 'operation': 0.0,
 'opt': 0.0,
 'option': 0.0,
 'optional': 0.0,
 'options': 0.0,
 'order': 0.0,
 'org': 0.0,
 'origin': 0.0,
 'original': 0.0,
 'os': 0.0,
 'output': 0.0,
 'outputs': 0.0,
 'overfitting': 0.0,
 'owner': 0.0,
 'package': 0.0,
 'packages': 0.0,
 'page': 0.0,
 'pandas': 0.0,
 'parameter': 0.0,
 'parameters': 0.0,
 'params': 0.0,
 'parquet': 0.0,
 'parse': 0.0,
 'particular': 0.0,
 'particularly': 0.0,
 'pass': 0.0,
 'passed': 0.0,
 'passing': 0.0,
 'password': 0.0,
 'paste': 0.0,
 'pastor': 0.0,
 'path': 0.0,
 'paths': 0.0,
 'pay': 0.0,
 'payment_type': 0.0,
 'pc': 0.0,
 'pd': 0.0,
 'peer': 0.0,
 'perform': 0.0,
 'performance': 0.0,
 'period': 0.0,
 'permission': 0.0,
 'permissions': 0.0,
 'pg': 0.0,
 'pgadmin': 0.0,
 'pgadmin4': 0.0,
 'pgadmin_default_email': 0.0,
 'pgadmin_default_password': 0.0,
 'pgcli': 0.0,
 'pgdatabase': 0.0,
 'pick': 0.0,
 'pickup_datetime': 0.0,
 'pip': 0.0,
 'pipeline': 0.0,
 'pipenv': 0.0,
 'pipfile': 0.0,
 'pl3mmuxubc_hihxl5ji8t4o6lpaophaclr': 0.0,
 'place': 0.0,
 'platform': 0.0,
 'platforms': 0.0,
 'plt': 0.0,
 'point': 0.0,
 'points': 0.0,
 'port': 0.0,
 'ports': 0.0,
 'position': 0.0,
 'possible': 0.0,
 'post': 0.0,
 'postgres': 0.0,
 'postgres_db': 0.0,
 'postgres_password': 0.0,
 'postgres_user': 0.0,
 'postgresql': 0.0,
 'powershell': 0.0,
 'pq': 0.0,
 'practice': 0.0,
 'pre': 0.0,
 'precision': 0.0,
 'predict': 0.0,
 'prediction': 0.0,
 'predictions': 0.0,
 'prefect': 0.0,
 'prefer': 0.0,
 'present': 0.0,
 'press': 0.0,
 'pretty': 0.0,
 'prevent': 0.0,
 'previous': 0.0,
 'previously': 0.0,
 'print': 0.0,
 'private': 0.0,
 'probably': 0.0,
 'problem': 0.0,
 'problems': 0.0,
 'proceed': 0.0,
 'process': 0.0,
 'processes': 0.0,
 'production': 0.0,
 'profile': 0.0,
 'program': 0.0,
 'programs': 0.0,
 'progress': 0.0,
 'project': 0.0,
 'project_id': 0.0,
 'projects': 0.0,
 'prompt': 0.0,
 'properly': 0.0,
 'protobuf': 0.0,
 'provide': 0.0,
 'provided': 0.0,
 'provides': 0.0,
 'ps': 0.0,
 'psql': 0.0,
 'psycopg2': 0.0,
 'pubhtml': 0.0,
 'public': 0.0,
 'pull': 0.0,
 'pulocationid': 0.0,
 'purpose': 0.0,
 'push': 0.0,
 'pwd': 0.0,
 'py': 0.0,
 'py4j': 0.0,
 'pyarrow': 0.0,
 'pyspark': 0.0,
 'python': 0.0,
 'python3': 0.0,
 'pythonpath': 0.0,
 'queries': 0.0,
 'query': 0.0,
 'question': 0.0,
 'questions': 0.0,
 'quinn': 0.0,
 'quite': 0.0,
 'quotes': 0.0,
 'radikal': 0.0,
 'raised': 0.0,
 'ram': 0.0,
 'ran': 0.0,
 'random': 0.0,
 'random_state': 0.0,
 'range': 0.0,
 'raw': 0.0,
 'read': 0.0,
 'read_csv': 0.0,
 'read_parquet': 0.0,
 'reading': 0.0,
 'ready': 0.0,
 'real': 0.0,
 'really': 0.0,
 'reason': 0.0,
 'recall': 0.0,
 'receive': 0.0,
 'recent': 0.0,
 'recognized': 0.0,
 'recommend': 0.0,
 'recommended': 0.0,
 'record': 0.0,
 'recorded': 0.0,
 'records': 0.0,
 'recreate': 0.0,
 'refer': 0.0,
 'reference': 0.0,
 'regarding': 0.0,
 'region': 0.0,
 'register': 0.0,
 'registry': 0.0,
 'regression': 0.0,
 'regularization': 0.0,
 'reinstall': 0.0,
 'related': 0.0,
 'releases': 0.0,
 'remember': 0.0,
 'remote': 0.0,
 'remove': 0.0,
 'removed': 0.0,
 'removing': 0.0,
 'rename': 0.0,
 'replace': 0.0,
 'replaced': 0.0,
 ...}

In [24]:
doc_dict = dict(zip(names, X.toarray()[1]))
doc_dict

{'01': 0.0,
 '02': 0.0,
 '03': 0.0,
 '04': 0.0,
 '05': 0.0,
 '06': 0.0,
 '09': 0.0,
 '10': 0.0,
 '100': 0.0,
 '11': 0.0,
 '12': 0.0,
 '127': 0.0,
 '13': 0.0,
 '14': 0.0,
 '15': 0.0,
 '16': 0.0,
 '17': 0.0,
 '19': 0.0,
 '1st': 0.0,
 '20': 0.0,
 '2019': 0.0,
 '2020': 0.0,
 '2021': 0.0,
 '2022': 0.0,
 '2023': 0.0,
 '2024': 0.0,
 '21': 0.0,
 '22': 0.0,
 '24': 0.0,
 '25': 0.0,
 '2pacx': 0.0,
 '30': 0.0,
 '35': 0.0,
 '403': 0.0,
 '42': 0.0,
 '50': 0.0,
 '5000': 0.0,
 '5431': 0.0,
 '5432': 0.0,
 '60': 0.0,
 '600': 0.0,
 '7077': 0.0,
 '80': 0.0,
 '8080': 0.0,
 '8888': 0.0,
 '9696': 0.0,
 'abhijit': 0.0,
 'able': 0.0,
 'abolade': 0.0,
 'absolute': 0.0,
 'accept': 0.0,
 'access': 0.0,
 'accordingly': 0.0,
 'account': 0.0,
 'accuracy': 0.0,
 'action': 0.0,
 'activate': 0.0,
 'actual': 0.0,
 'actually': 0.0,
 'add': 0.0,
 'added': 0.0,
 'adding': 0.0,
 'addition': 0.0,
 'additional': 0.0,
 'additionally': 0.0,
 'address': 0.0,
 'admin': 0.0,
 'advani': 0.0,
 'ahmed': 0.0,
 'ai': 0.0,
 'airflow': 0.0,
 'alejandro': 0.0,
 'alena': 0.0,
 'alex': 0.0,
 'alexey': 0.0,
 'alexeygrigorev': 0.0,
 'allocate': 0.0,
 'allow': 0.0,
 'allowed': 0.0,
 'allowing': 0.0,
 'allows': 0.0,
 'alpha': 0.0,
 'alternative': 0.0,
 'alternatively': 0.0,
 'amazon': 0.0,
 'amazonaws': 0.0,
 'amd64': 0.0,
 'aminat': 0.0,
 'anaconda': 0.0,
 'anaconda3': 0.0,
 'analytics': 0.0,
 'anand': 0.0,
 'andrii': 0.0,
 'ans': 0.0,
 'answer': 0.0,
 'answered': 0.0,
 'answers': 0.0,
 'apache': 0.0,
 'api': 0.0,
 'aponte': 0.0,
 'app': 0.0,
 'appear': 0.0,
 'appears': 0.0,
 'append': 0.0,
 'application': 0.0,
 'apply': 0.0,
 'appname': 0.0,
 'approach': 0.0,
 'apt': 0.0,
 'architecture': 0.0,
 'archives': 0.0,
 'args': 0.0,
 'argument': 0.0,
 'array': 0.0,
 'arrays': 0.0,
 'article': 0.0,
 'asia': 0.0,
 'ask': 0.0,
 'asked': 0.0,
 'asks': 0.0,
 'assigned': 0.0,
 'astype': 0.0,
 'attempting': 0.0,
 'attribute': 0.0,
 'attributeerror': 0.0,
 'auc': 0.0,
 'auth': 0.0,
 'authenticate': 0.0,
 'authentication': 0.0,
 'auto': 0.0,
 'automatically': 0.0,
 'available': 0.0,
 'average': 0.0,
 'avila': 0.0,
 'avoid': 0.0,
 'aws': 0.0,
 'azure': 0.0,
 'backend': 0.0,
 'bad': 0.0,
 'bar': 0.0,
 'base': 0.0,
 'based': 0.0,
 'bash': 0.0,
 'bashrc': 0.0,
 'basically': 0.0,
 'batch': 0.0,
 'best': 0.0,
 'better': 0.0,
 'bhaskar': 0.0,
 'bhatia': 0.0,
 'big': 0.0,
 'bigquery': 0.0,
 'billing': 0.0,
 'bin': 0.0,
 'binary': 0.0,
 'bind': 0.0,
 'bit': 0.0,
 'blob': 0.0,
 'block': 0.0,
 'blog': 0.0,
 'box': 0.0,
 'bq': 0.0,
 'branch': 0.0,
 'brew': 0.0,
 'brigida': 0.0,
 'browser': 0.0,
 'bucket': 0.0,
 'build': 0.0,
 'builder': 0.0,
 'building': 0.0,
 'built': 0.0,
 'calculate': 0.0,
 'calderin': 0.0,
 'called': 0.0,
 'calling': 0.0,
 'capstone': 0.0,
 'capture': 0.0,
 'care': 0.0,
 'careful': 0.0,
 'case': 0.0,
 'cast': 0.0,
 'cat': 0.0,
 'categorical': 0.0,
 'cause': 0.0,
 'caused': 0.0,
 'causing': 0.0,
 'cd': 0.0,
 'cell': 0.0,
 'certificate': 0.0,
 'chakraborty': 0.0,
 'change': 0.0,
 'changed': 0.0,
 'changes': 0.0,
 'changing': 0.0,
 'channel': 0.0,
 'check': 0.0,
 'checking': 0.0,
 'chizhmak': 0.0,
 'chmod': 0.0,
 'choice': 0.0,
 'choose': 0.0,
 'chown': 0.0,
 'churn': 0.0,
 'ci': 0.0,
 'class': 0.0,
 'classes': 0.0,
 'classification': 0.0,
 'clear': 0.0,
 'cli': 0.0,
 'click': 0.0,
 'client': 0.0,
 'clone': 0.0,
 'close': 0.0,
 'closed': 0.0,
 'closest': 0.0,
 'clothing': 0.0,
 'cloud': 0.0,
 'cloudfront': 0.0,
 'club': 0.0,
 'cluster': 0.0,
 'cmd': 0.0,
 'code': 0.0,
 'codespaces': 0.0,
 'coding': 0.0,
 'cohort': 0.0,
 'cohorts': 0.0,
 'col': 0.0,
 'colab': 0.0,
 'column': 0.0,
 'columns': 0.0,
 'com': 0.0,
 'command': 0.0,
 'commands': 0.0,
 'commit': 0.0,
 'common': 0.0,
 'community': 0.0,
 'compatibility': 0.0,
 'compatible': 0.0,
 'complete': 0.0,
 'completed': 0.0,
 'compose': 0.0,
 'compute': 0.0,
 'computer': 0.0,
 'conda': 0.0,
 'config': 0.0,
 'configuration': 0.0,
 'configure': 0.0,
 'configured': 0.0,
 'confirm': 0.0,
 'connect': 0.0,
 'connecting': 0.0,
 'connection': 0.0,
 'connector': 0.0,
 'consider': 0.0,
 'consistent': 0.0,
 'console': 0.0,
 'contain': 0.0,
 'container': 0.0,
 'containers': 0.0,
 'contains': 0.0,
 'content': 0.0,
 'contents': 0.0,
 'context': 0.0,
 'continue': 0.0,
 'control': 0.0,
 'convert': 0.0,
 'converted': 0.0,
 'copy': 0.0,
 'core': 0.0,
 'correct': 0.0,
 'correctly': 0.0,
 'correlation': 0.0,
 'corresponding': 0.0,
 'couldn': 0.0,
 'course': 0.0,
 'cp': 0.0,
 'cpu': 0.0,
 'create': 0.0,
 'create_engine': 0.0,
 'created': 0.0,
 'creates': 0.0,
 'creating': 0.0,
 'creation': 0.0,
 'credentials': 0.0,
 'credit': 0.0,
 'crucial': 0.0,
 'csv': 0.0,
 'ctrl': 0.0,
 'curl': 0.0,
 'current': 0.0,
 'custom': 0.0,
 'd37ci6vzurychx': 0.0,
 'daemon': 0.0,
 'daniel': 0.0,
 'dashboard': 0.0,
 'data': 0.3127766226016382,
 'database': 0.0,
 'dataframe': 0.0,
 'dataframes': 0.0,
 'dataproc': 0.0,
 'dataset': 0.0,
 'datasets': 0.0,
 'datatalks': 0.0,
 'datatalksclub': 0.5316383823591385,
 'datatype': 0.0,
 'date': 0.0,
 'datetime': 0.0,
 'david': 0.0,
 'day': 0.0,
 'db': 0.0,
 'dbt': 0.0,
 'dbt_project': 0.0,
 'deadline': 0.0,
 'dealing': 0.0,
 'debian': 0.0,
 'debug': 0.0,
 'deep': 0.0,
 'def': 0.0,
 'default': 0.0,
 'define': 0.0,
 'defined': 0.0,
 'definition': 0.0,
 'delete': 0.0,
 'deleted': 0.0,
 'deleting': 0.0,
 'denied': 0.0,
 'dependencies': 0.0,
 'dependency': 0.0,
 'deploy': 0.0,
 'deploying': 0.0,
 'deployment': 0.0,
 'deprecated': 0.0,
 'description': 0.0,
 'desktop': 0.0,
 'detailed': 0.0,
 'details': 0.0,
 'dev': 0.0,
 'development': 0.0,
 'deviation': 0.0,
 'device': 0.0,
 'df': 0.0,
 'df_train': 0.0,
 'dict': 0.0,
 'dictionary': 0.0,
 'dictvectorizer': 0.0,
 'did': 0.0,
 'didn': 0.0,
 'difference': 0.0,
 'different': 0.0,
 'dino': 0.0,
 'dir': 0.0,
 'directly': 0.0,
 'directory': 0.0,
 'disk': 0.0,
 'distribution': 0.0,
 'doc': 0.0,
 'docker': 0.0,
 'dockerfile': 0.0,
 'docs': 0.0,
 'document': 0.0,
 'documentation': 0.0,
 'does': 0.0,
 'doesn': 0.0,
 'doing': 0.0,
 'dolocationid': 0.0,
 'don': 0.0,
 'dot': 0.0,
 'double': 0.0,
 'downgrade': 0.0,
 'download': 0.0,
 'downloaded': 0.0,
 'downloading': 0.0,
 'downloads': 0.0,
 'dpage': 0.0,
 'dragon': 0.0,
 'drive': 0.0,
 'drop': 0.0,
 'dropoff_datetime': 0.0,
 'dropping': 0.0,
 'dt': 0.0,
 'dtc': 0.0,
 'duration': 0.0,
 'dv': 0.0,
 'easier': 0.0,
 'easiest': 0.0,
 'easily': 0.0,
 'ec2': 0.0,
 'echo': 0.0,
 'ecr': 0.0,
 'edit': 0.0,
 'editing': 0.0,
 'editor': 0.0,
 'email': 0.0,
 'en': 0.0,
 'enable': 0.0,
 'enabled': 0.0,
 'encode': 0.0,
 'encoding': 0.0,
 'encounter': 0.0,
 'encountered': 0.0,
 'end': 0.0,
 'endpoint': 0.0,
 'engine': 0.0,
 'engineering': 0.5401030373894639,
 'ensure': 0.0,
 'enter': 0.0,
 'entire': 0.0,
 'entries': 0.0,
 'env': 0.0,
 'environ': 0.0,
 'environment': 0.0,
 'environments': 0.0,
 'equal': 0.0,
 'erick': 0.0,
 'error': 0.0,
 'errors': 0.0,
 'escape': 0.0,
 'especially': 0.0,
 'eu': 0.0,
 'europe': 0.0,
 'evaluate': 0.0,
 'evaluated': 0.0,
 'evaluation': 0.0,
 'exactly': 0.0,
 'example': 0.0,
 'exception': 0.0,
 'exe': 0.0,
 'exec': 0.0,
 'executable': 0.0,
 'execute': 0.0,
 'executed': 0.0,
 'executing': 0.0,
 'execution': 0.0,
 'exist': 0.0,
 'existing': 0.0,
 'exists': 0.0,
 'exit': 0.0,
 'expected': 0.0,
 'experiment': 0.0,
 'explanation': 0.0,
 'explicitly': 0.0,
 'export': 0.0,
 'extension': 0.0,
 'external': 0.0,
 'extra': 0.0,
 'extract': 0.0,
 'face': 0.0,
 'faced': 0.0,
 'fact': 0.0,
 'fact_trips': 0.0,
 'fail': 0.0,
 'failed': 0.0,
 'failing': 0.0,
 'fails': 0.0,
 'false': 0.0,
 'faq': 0.0,
 'fatal': 0.0,
 'feature': 0.0,
 'features': 0.0,
 'fetch': 0.0,
 'fhv': 0.0,
 'fhv_tripdata_2019': 0.0,
 'field': 0.0,
 'figure': 0.0,
 'file': 0.0,
 'files': 0.0,
 'filesystem': 0.0,
 'filter': 0.0,
 'final': 0.0,
 'finally': 0.0,
 'findspark': 0.0,
 'fine': 0.0,
 'fit': 0.0,
 'fix': 0.0,
 'fixed': 0.0,
 'flag': 0.0,
 'flask': 0.0,
 'float': 0.0,
 'float64': 0.0,
 'flow': 0.0,
 'folder': 0.0,
 'folders': 0.0,
 'follow': 0.0,
 'followed': 0.0,
 'following': 0.0,
 'follows': 0.0,
 'forbidden': 0.0,
 'force': 0.0,
 'forget': 0.0,
 'forgot': 0.0,
 'form': 0.0,
 'format': 0.0,
 'forms': 0.0,
 'forward': 0.0,
 'fouesnard': 0.0,
 'free': 0.0,
 'fresh': 0.0,
 'fs': 0.0,
 'function': 0.0,
 'functions': 0.0,
 'future': 0.0,
 'gateway': 0.0,
 'gcloud': 0.0,
 'gcp': 0.0,
 'gcs': 0.0,
 'generate': 0.0,
 'generated': 0.0,
 'generator': 0.0,
 'george': 0.0,
 'get_dummies': 0.0,
 'get_feature_names_out': 0.0,
 'getdbt': 0.0,
 'getorcreate': 0.0,
 'gets': 0.0,
 'getting': 0.0,
 'git': 0.0,
 'github': 0.3792268345828722,
 'githubusercontent': 0.0,
 'gitignore': 0.0,
 'given': 0.0,
 'gives': 0.0,
 'gmail': 0.0,
 'going': 0.0,
 'good': 0.0,
 'google': 0.0,
 'google_application_credentials': 0.0,
 'googleapi': 0.0,
 'googleapis': 0.0,
 'got': 0.0,
 'gpu': 0.0,
 'great': 0.0,
 'green': 0.0,
 'grigorev': 0.0,
 'group': 0.0,
 'gs': 0.0,
 'guide': 0.0,
 'gunicorn': 0.0,
 'gz': 0.0,
 'gzip': 0.0,
 'hadoop': 0.0,
 'hadoop3': 0.0,
 'hand': 0.0,
 'handle': 0.0,
 'happen': 0.0,
 'happens': 0.0,
 'haven': 0.0,
 'having': 0.0,
 'head': 0.0,
 'help': 0.0,
 'helped': 0.0,
 'helps': 0.0,
 'high': 0.0,
 'higher': 0.0,
 'highly': 0.0,
 'home': 0.0,
 'homebrew': 0.0,
 'homework': 0.0,
 'homeworks': 0.0,
 'hope': 0.0,
 'host': 0.0,
 'hostname': 0.0,
 'hot': 0.0,
 'hours': 0.0,
 'housing': 0.0,
 'hrithik': 0.0,
 'html': 0.0,
 'http': 0.0,
 'https': 0.0,
 'humberto': 0.0,
 'hw': 0.0,
 'hws': 0.0,
 'iam': 0.0,
 'icon': 0.0,
 'id': 0.0,
 'ide': 0.0,
 'idea': 0.0,
 'ignore': 0.0,
 'image': 0.0,
 'images': 0.0,
 'immediately': 0.0,
 'import': 0.0,
 'importance': 0.0,
 'important': 0.0,
 'importerror': 0.0,
 'importing': 0.0,
 'include': 0.0,
 'included': 0.0,
 'including': 0.0,
 'increase': 0.0,
 'index': 0.0,
 'info': 0.0,
 'information': 0.0,
 'init': 0.0,
 'initial': 0.0,
 'input': 0.0,
 'inside': 0.0,
 'install': 0.0,
 'installation': 0.0,
 'installed': 0.0,
 'installing': 0.0,
 'instance': 0.0,
 'instances': 0.0,
 'instead': 0.0,
 'instruction': 0.0,
 'instructions': 0.0,
 'insufficient': 0.0,
 'int': 0.0,
 'int64': 0.0,
 'integer': 0.0,
 'interesting': 0.0,
 'interface': 0.0,
 'internal': 0.0,
 'internet': 0.0,
 'interpreter': 0.0,
 'intro': 0.0,
 'invalid': 0.0,
 'io': 0.0,
 'ip': 0.0,
 'ipynb': 0.0,
 'isn': 0.0,
 'issue': 0.0,
 'issues': 0.0,
 'iteration': 0.0,
 'ivan': 0.0,
 'jan': 0.0,
 'jar': 0.0,
 'java': 0.0,
 'java_home': 0.0,
 'job': 0.0,
 'jobs': 0.0,
 'join': 0.0,
 'json': 0.0,
 'jupyter': 0.0,
 'just': 0.0,
 'kafka': 0.0,
 'kaggle': 0.0,
 'keras': 0.0,
 'kernel': 0.0,
 'key': 0.0,
 'keys': 0.0,
 'kill': 0.0,
 'kind': 0.0,
 'kinesis': 0.0,
 'kniazeva': 0.0,
 'know': 0.0,
 'known': 0.0,
 'konrad': 0.0,
 'krishna': 0.0,
 'kubectl': 0.0,
 'kubernetes': 0.0,
 'kumar': 0.0,
 'kwargs': 0.0,
 'lambda': 0.0,
 'laptop': 0.0,
 'large': 0.0,
 'larkin': 0.0,
 'later': 0.0,
 'latest': 0.0,
 'launch': 0.0,
 'layer': 0.0,
 'layers': 0.0,
 'lead': 0.0,
 'leaderboard': 0.0,
 'learn': 0.0,
 'learning': 0.0,
 'left': 0.0,
 'length': 0.0,
 'lesson': 0.0,
 'lessons': 0.0,
 'let': 0.0,
 'level': 0.0,
 'lib': 0.0,
 'libraries': 0.0,
 'library': 0.0,
 'like': 0.0,
 'likely': 0.0,
 'line': 0.0,
 'linear': 0.0,
 'lines': 0.0,
 'link': 0.0,
 'links': 0.0,
 'linux': 0.0,
 'list': 0.0,
 'listed': 0.0,
 'litvinov': 0.0,
 'live': 0.0,
 'll': 0.0,
 'load': 0.0,
 'loaded': 0.0,
 'loading': 0.0,
 'local': 0.0,
 'localhost': 0.0,
 'locally': 0.0,
 'located': 0.0,
 'location': 0.0,
 'locations': 0.0,
 'lock': 0.0,
 'log': 0.0,
 'logged': 0.0,
 'login': 0.0,
 'logistic': 0.0,
 'logs': 0.0,
 'long': 0.0,
 'longer': 0.0,
 'look': 0.0,
 'looking': 0.0,
 'looks': 0.0,
 'loop': 0.0,
 'lot': 0.0,
 'lower': 0.0,
 'ls': 0.0,
 'lukafiardi': 0.0,
 'mac': 0.0,
 'machine': 0.0,
 'macos': 0.0,
 'mage': 0.0,
 'magic': 0.0,
 'main': 0.0,
 'make': 0.0,
 'makes': 0.0,
 'making': 0.0,
 'manage': 0.0,
 'manually': 0.0,
 'map': 0.0,
 'marcos': 0.0,
 'marcosmjd': 0.0,
 'martin': 0.0,
 'master': 0.0,
 'match': 0.0,
 'matplotlib': 0.0,
 'matrix': 0.0,
 'max': 0.0,
 'maybe': 0.0,
 'md': 0.0,
 'mean': 0.0,
 'mean_squared_error': 0.0,
 'means': 0.0,
 'media': 0.0,
 'median_house_value': 0.0,
 'memoona': 0.0,
 'memory': 0.0,
 'mentioned': 0.0,
 'merge': 0.0,
 'message': 0.0,
 'metadata': 0.0,
 'method': 0.0,
 'metrics': 0.0,
 'microsoft': 0.0,
 'midterm': 0.0,
 'minutes': 0.0,
 'missing': 0.0,
 'mkdir': 0.0,
 'ml': 0.0,
 'mlbookcamp': 0.0,
 'mlflow': 0.0,
 'mlops': 0.0,
 'mode': 0.0,
 'model': 0.0,
 'models': 0.0,
 'modified': 0.0,
 'modify': 0.0,
 'module': 0.0,
 'modulenotfounderror': 0.0,
 'modules': 0.0,
 'month': 0.0,
 'mount': 0.0,
 'moved': 0.0,
 'multiple': 0.0,
 'multiplication': 0.0,
 'mélanie': 0.0,
 'named': 0.0,
 'names': 0.0,
 'nan': 0.0,
 'nano': 0.0,
 'native': 0.0,
 'navigate': 0.0,
 'ndarray': 0.0,
 'necessary': 0.0,
 'need': 0.0,
 'needed': 0.0,
 'needs': 0.0,
 'negative': 0.0,
 'net': 0.0,
 'network': 0.0,
 'networks': 0.0,
 'new': 0.0,
 'newly': 0.0,
 'non': 0.0,
 'normal': 0.0,
 'note': 0.0,
 'notebook': 0.0,
 'notebooks': 0.0,
 'notes': 0.0,
 'notice': 0.0,
 'np': 0.0,
 'nukta': 0.0,
 'null': 0.0,
 'number': 0.0,
 'numeric': 0.0,
 'numerical': 0.0,
 'numpy': 0.0,
 'ny': 0.0,
 'ny_taxi': 0.0,
 'ny_taxi_postgres_data': 0.0,
 'nyc': 0.0,
 'object': 0.0,
 'observations': 0.0,
 'occur': 0.0,
 'occurred': 0.0,
 'occurs': 0.0,
 'odimegwu': 0.0,
 'office': 0.0,
 'official': 0.0,
 'ok': 0.0,
 'old': 0.0,
 'older': 0.0,
 'olga': 0.0,
 'onehotencoder': 0.0,
 'ones': 0.0,
 'open': 0.0,
 'operation': 0.0,
 'opt': 0.0,
 'option': 0.0,
 'optional': 0.0,
 'options': 0.0,
 'order': 0.0,
 'org': 0.0,
 'origin': 0.0,
 'original': 0.0,
 'os': 0.0,
 'output': 0.0,
 'outputs': 0.0,
 'overfitting': 0.0,
 'owner': 0.0,
 'package': 0.0,
 'packages': 0.0,
 'page': 0.0,
 'pandas': 0.0,
 'parameter': 0.0,
 'parameters': 0.0,
 'params': 0.0,
 'parquet': 0.0,
 'parse': 0.0,
 'particular': 0.0,
 'particularly': 0.0,
 'pass': 0.0,
 'passed': 0.0,
 'passing': 0.0,
 'password': 0.0,
 'paste': 0.0,
 'pastor': 0.0,
 'path': 0.0,
 'paths': 0.0,
 'pay': 0.0,
 'payment_type': 0.0,
 'pc': 0.0,
 'pd': 0.0,
 'peer': 0.0,
 'perform': 0.0,
 'performance': 0.0,
 'period': 0.0,
 'permission': 0.0,
 'permissions': 0.0,
 'pg': 0.0,
 'pgadmin': 0.0,
 'pgadmin4': 0.0,
 'pgadmin_default_email': 0.0,
 'pgadmin_default_password': 0.0,
 'pgcli': 0.0,
 'pgdatabase': 0.0,
 'pick': 0.0,
 'pickup_datetime': 0.0,
 'pip': 0.0,
 'pipeline': 0.0,
 'pipenv': 0.0,
 'pipfile': 0.0,
 'pl3mmuxubc_hihxl5ji8t4o6lpaophaclr': 0.0,
 'place': 0.0,
 'platform': 0.0,
 'platforms': 0.0,
 'plt': 0.0,
 'point': 0.0,
 'points': 0.0,
 'port': 0.0,
 'ports': 0.0,
 'position': 0.0,
 'possible': 0.0,
 'post': 0.0,
 'postgres': 0.0,
 'postgres_db': 0.0,
 'postgres_password': 0.0,
 'postgres_user': 0.0,
 'postgresql': 0.0,
 'powershell': 0.0,
 'pq': 0.0,
 'practice': 0.0,
 'pre': 0.0,
 'precision': 0.0,
 'predict': 0.0,
 'prediction': 0.0,
 'predictions': 0.0,
 'prefect': 0.0,
 'prefer': 0.0,
 'present': 0.0,
 'press': 0.0,
 'pretty': 0.0,
 'prevent': 0.0,
 'previous': 0.0,
 'previously': 0.0,
 'print': 0.0,
 'private': 0.0,
 'probably': 0.0,
 'problem': 0.0,
 'problems': 0.0,
 'proceed': 0.0,
 'process': 0.0,
 'processes': 0.0,
 'production': 0.0,
 'profile': 0.0,
 'program': 0.0,
 'programs': 0.0,
 'progress': 0.0,
 'project': 0.0,
 'project_id': 0.0,
 'projects': 0.0,
 'prompt': 0.0,
 'properly': 0.0,
 'protobuf': 0.0,
 'provide': 0.0,
 'provided': 0.0,
 'provides': 0.0,
 'ps': 0.0,
 'psql': 0.0,
 'psycopg2': 0.0,
 'pubhtml': 0.0,
 'public': 0.0,
 'pull': 0.0,
 'pulocationid': 0.0,
 'purpose': 0.0,
 'push': 0.0,
 'pwd': 0.0,
 'py': 0.0,
 'py4j': 0.0,
 'pyarrow': 0.0,
 'pyspark': 0.0,
 'python': 0.0,
 'python3': 0.0,
 'pythonpath': 0.0,
 'queries': 0.0,
 'query': 0.0,
 'question': 0.0,
 'questions': 0.0,
 'quinn': 0.0,
 'quite': 0.0,
 'quotes': 0.0,
 'radikal': 0.0,
 'raised': 0.0,
 'ram': 0.0,
 'ran': 0.0,
 'random': 0.0,
 'random_state': 0.0,
 'range': 0.0,
 'raw': 0.0,
 'read': 0.0,
 'read_csv': 0.0,
 'read_parquet': 0.0,
 'reading': 0.0,
 'ready': 0.0,
 'real': 0.0,
 'really': 0.0,
 'reason': 0.0,
 'recall': 0.0,
 'receive': 0.0,
 'recent': 0.0,
 'recognized': 0.0,
 'recommend': 0.0,
 'recommended': 0.0,
 'record': 0.0,
 'recorded': 0.0,
 'records': 0.0,
 'recreate': 0.0,
 'refer': 0.0,
 'reference': 0.0,
 'regarding': 0.0,
 'region': 0.0,
 'register': 0.0,
 'registry': 0.0,
 'regression': 0.0,
 'regularization': 0.0,
 'reinstall': 0.0,
 'related': 0.0,
 'releases': 0.0,
 'remember': 0.0,
 'remote': 0.0,
 'remove': 0.0,
 'removed': 0.0,
 'removing': 0.0,
 'rename': 0.0,
 'replace': 0.0,
 'replaced': 0.0,
 ...}

In [25]:
X.dot(q.T).todense() #this is cosine similarity

matrix([[0.48049682],
        [0.        ],
        [0.        ],
        [0.2083882 ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.17557272],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.15870689],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.09680922],
        [0.        ],
        [0.        ],
        [0.07529201],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.29986763],
        [0.10520675],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.27447476],
        [0.12828407],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.05163407],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03156309],
        [0.04914818],
        [0.07138962],
        [0.        ],
        [0.04329773],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02804374],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.06739038],
        [0.        ],
        [0.00980845],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.05820102],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.05020173],
        [0.        ],
        [0.        ],
        [0.0605701 ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.05101782],
        [0.        ],
        [0.        ],
        [0.04327901],
        [0.        ],
        [0.03089898],
        [0.        ],
        [0.        ],
        [0.05106564],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.08232505],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02129978],
        [0.        ],
        [0.0308046 ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.16499001],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03561953],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.07733187],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.12621053],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.01502752],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.05398514],
        [0.        ],
        [0.05115414],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03869534],
        [0.04112908],
        [0.03728758],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.09064943],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.04233182],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.07784175],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02591152],
        [0.        ],
        [0.03451997],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.04143129],
        [0.        ],
        [0.05407899],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.22471032],
        [0.04931254],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03820044],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02533066],
        [0.04085302],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.07593909],
        [0.0723982 ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.01328652],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.10202387],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.038628  ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.12084703],
        [0.10694586],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.08997023],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.05839441],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.12589674],
        [0.196371  ],
        [0.        ],
        [0.        ],
        [0.06058604],
        [0.35656584],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.16267179],
        [0.        ],
        [0.        ],
        [0.30485152],
        [0.33773583],
        [0.1231099 ],
        [0.13606474],
        [0.26771296],
        [0.        ],
        [0.10835741],
        [0.13944604],
        [0.03865125],
        [0.18083089],
        [0.03179529],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.05501329],
        [0.03482028],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.06558528],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03200722],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.05236864],
        [0.0581809 ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.10647026],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03710508],
        [0.        ],
        [0.        ],
        [0.04720167],
        [0.        ],
        [0.        ],
        [0.04364401],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03714607],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.04808267],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.14400322],
        [0.        ],
        [0.        ],
        [0.03667548],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.06555259],
        [0.13437698],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.05902352],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.01885244],
        [0.03485812],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.05249485],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.06591061],
        [0.        ],
        [0.        ],
        [0.05969678],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.0284637 ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.06244092],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02243907],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.15333692],
        [0.        ],
        [0.03506481],
        [0.18859024],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03423508],
        [0.        ],
        [0.        ],
        [0.01588394],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.04924389],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.05098356],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03294308],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03026252],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02958017],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.07023608],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.04109976],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.04644028],
        [0.        ],
        [0.        ],
        [0.03833017],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.0364746 ],
        [0.08415092],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02442063],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.12810532],
        [0.05637395],
        [0.04826177],
        [0.        ],
        [0.04906345],
        [0.        ],
        [0.26727441],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.11135001],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.06894246],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.0685693 ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.04106944],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.06551955],
        [0.        ],
        [0.07186382],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.06333884],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.12685281],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.07782842],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02660461],
        [0.06140912],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.05395122],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02053581],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02983282],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03416571],
        [0.03748537],
        [0.        ],
        [0.05747492],

In [26]:
# In practice, we usually use cosine similarity:

score = cosine_similarity(X, q).flatten()

In [27]:
score

array([0.48049682, 0.        , 0.        , 0.2083882 , 0.        ,
       0.        , 0.        , 0.17557272, 0.        , 0.        ,
       0.        , 0.15870689, 0.        , 0.        , 0.        ,
       0.09680922, 0.        , 0.        , 0.07529201, 0.        ,
       0.        , 0.        , 0.29986763, 0.10520675, 0.        ,
       0.        , 0.        , 0.27447476, 0.12828407, 0.        ,
       0.        , 0.        , 0.        , 0.05163407, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.03156309,
       0.04914818, 0.07138962, 0.        , 0.04329773, 0.        ,
       0.        , 0.        , 0.        , 0.02804374, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.06739038, 0.        , 0.00980845,
       0.        , 0.        , 0.        , 0.        , 0.05820102,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.05020173, 0.        , 0.        , 0.0605701 , 0.        ,
       0.        , 0.        , 0.        , 0.05101782, 0.        ,
       0.        , 0.04327901, 0.        , 0.03089898, 0.        ,
       0.        , 0.05106564, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.08232505, 0.        , 0.        , 0.        , 0.02129978,
       0.        , 0.0308046 , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.16499001, 0.        ,
       0.        , 0.        , 0.03561953, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.07733187, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.12621053, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.01502752, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.05398514, 0.        , 0.05115414, 0.        , 0.        ,
       0.        , 0.        , 0.03869534, 0.04112908, 0.03728758,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.09064943, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.04233182,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07784175, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.02591152, 0.        , 0.03451997, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.04143129, 0.        , 0.05407899, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.22471032, 0.04931254, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.03820044, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.02533066, 0.04085302, 0.        , 0.        ,
       0.        , 0.        , 0.07593909, 0.0723982 , 0.        ,
       0.        , 0.        , 0.        , 0.01328652, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.10202387, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.038628  , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.12084703, 0.10694586, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.08997023, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.05839441, 0.        , 0.        , 0.        , 0.        ,
       0.12589674, 0.196371  , 0.        , 0.        , 0.06058604,
       0.35656584, 0.        , 0.        , 0.        , 0.        ,
       0.16267179, 0.        , 0.        , 0.30485152, 0.33773583,
       0.1231099 , 0.13606474, 0.26771296, 0.        , 0.10835741,
       0.13944604, 0.03865125, 0.18083089, 0.03179529, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.05501329,
       0.03482028, 0.        , 0.        , 0.        , 0.        ,
       0.06558528, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.03200722, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.05236864, 0.0581809 , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.10647026, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.03710508, 0.        , 0.        ,
       0.04720167, 0.        , 0.        , 0.04364401, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.03714607, 0.        , 0.        ,
       0.        , 0.04808267, 0.        , 0.        , 0.        ,
       0.14400322, 0.        , 0.        , 0.03667548, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.06555259, 0.13437698, 0.        ,
       0.        , 0.        , 0.        , 0.05902352, 0.        ,
       0.        , 0.        , 0.        , 0.01885244, 0.03485812,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.05249485,
       0.        , 0.        , 0.        , 0.06591061, 0.        ,
       0.        , 0.05969678, 0.        , 0.        , 0.        ,
       0.0284637 , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.06244092,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.02243907, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.15333692,
       0.        , 0.03506481, 0.18859024, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.03423508,
       0.        , 0.        , 0.01588394, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.04924389, 0.        , 0.        , 0.        ,
       0.05098356, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.03294308, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.03026252, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.02958017, 0.        , 0.        , 0.        , 0.07023608,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.04109976, 0.        , 0.        , 0.        , 0.04644028,
       0.        , 0.        , 0.03833017, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.0364746 , 0.08415092, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.02442063,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.12810532, 0.05637395,
       0.04826177, 0.        , 0.04906345, 0.        , 0.26727441,
       0.        , 0.        , 0.        , 0.11135001, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.06894246,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.0685693 , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.04106944, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.06551955,
       0.        , 0.07186382, 0.        , 0.        , 0.        ,
       0.06333884, 0.        , 0.        , 0.        , 0.12685281,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07782842, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.02660461, 0.06140912, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.05395122, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.02053581, 0.        , 0.        , 0.        ,
       0.        , 0.02983282, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.03416571, 0.03748537, 0.        , 0.05747492, 0.        ,
       0.        , 0.        , 0.        , 0.13556595, 0.        ,
       0.10025904, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.03278609, 0.11688021, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.03662924, 0.0451592 , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        ])

In [28]:
np.argsort(score) #these are indexes of the documents with highest score, starts from zero score, 
# so the highest score is at the end

array([473, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613,
       614, 615, 616, 617, 618, 620, 621, 622, 624, 625, 627, 601, 628,
       600, 596, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580,
       581, 582, 583, 584, 585, 586, 589, 590, 591, 592, 594, 595, 597,
       569, 629, 632, 665, 666, 667, 668, 670, 671, 673, 674, 675, 676,
       677, 678, 679, 680, 682, 683, 684, 686, 687, 688, 689, 690, 691,
       664, 631, 663, 661, 633, 634, 635, 636, 637, 638, 640, 641, 642,
       643, 644, 645, 646, 647, 649, 650, 651, 652, 653, 655, 658, 659,
       660, 662, 692, 567, 564, 478, 479, 480, 481, 482, 483, 484, 486,
       487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499,
       500, 501, 477, 504, 476, 474, 433, 434, 437, 438, 441, 442, 443,
       444, 446, 447, 453, 459, 460, 461, 462, 463, 466, 467, 468, 469,
       471, 472, 946, 475, 566, 505, 507, 539, 540, 541, 542, 543, 544,
       545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 558,
       559, 560, 562, 563, 538, 506, 537, 535, 508, 509, 510, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 523, 524, 526, 527, 529,
       530, 531, 532, 533, 534, 536, 432, 694, 696, 855, 856, 859, 860,
       861, 862, 863, 864, 865, 866, 868, 869, 870, 871, 872, 873, 874,
       875, 876, 877, 878, 879, 880, 854, 881, 853, 851, 828, 829, 830,
       831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843,
       844, 845, 846, 847, 848, 849, 850, 852, 827, 882, 884, 919, 920,
       921, 924, 925, 926, 927, 928, 929, 930, 931, 934, 935, 936, 937,
       938, 939, 940, 941, 942, 943, 944, 945, 918, 883, 917, 914, 885,
       886, 887, 888, 889, 890, 892, 893, 894, 895, 897, 898, 899, 900,
       901, 902, 903, 904, 907, 909, 910, 911, 912, 916, 695, 825, 823,
       728, 730, 731, 733, 734, 735, 736, 737, 738, 739, 742, 743, 744,
       745, 746, 747, 748, 750, 751, 752, 753, 754, 755, 727, 756, 726,
       723, 697, 698, 699, 701, 702, 703, 704, 705, 706, 707, 708, 709,
       710, 711, 712, 713, 714, 716, 717, 718, 720, 721, 722, 724, 824,
       757, 763, 796, 797, 798, 799, 800, 801, 802, 803, 805, 807, 808,
       809, 811, 812, 813, 815, 816, 817, 818, 819, 820, 821, 822, 795,
       761, 794, 792, 765, 766, 767, 769, 770, 771, 772, 773, 775, 776,
       777, 778, 779, 781, 782, 783, 784, 785, 786, 788, 789, 790, 791,
       793, 431, 947, 429, 169, 170, 171, 175, 176, 177, 178, 179, 180,
       181, 168, 182, 184, 185, 186, 187, 188, 189, 190, 191, 192, 194,
       183, 166, 164, 163, 137, 138, 139, 140, 141, 143, 144, 145, 146,
       147, 149, 150, 151, 152, 153, 154, 155, 156, 157, 159, 160, 161,
       162, 195, 196, 197, 198, 229, 230, 231, 232, 233, 234, 235, 236,
       237, 238, 239, 240, 242, 244, 245, 246, 247, 248, 249, 250, 251,
       252, 253, 228, 136, 227, 224, 199, 200, 201, 202, 203, 204, 205,
       206, 207, 208, 210, 211, 212, 213, 214, 215, 216, 217, 218, 220,
       221, 222, 223, 225, 254, 135, 133,  38,  42,  44,  45,  46,  47,
        49,  50,  51,  52,  37,  53,  55,  56,  57,  58,  59,  60,  61,
        63,  65,  66,  54,  36,  35,  34,   1,   2,   4,   5,   6,   8,
         9,  10,  12,  13,  14,  16,  17,  19,  20,  21,  24,  25,  26,
        29,  30,  31,  32,  67,  68,  70,  71, 108, 109, 110, 111, 112,
       114, 115, 116, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
       128, 129, 130, 131, 132, 107, 134, 105, 102,  72,  73,  74,  76,
        77,  79,  80,  81,  82,  84,  85,  87,  89,  90,  92,  93,  94,
        95,  96,  97,  98,  99, 101, 103, 255, 219, 257, 354, 355, 356,
       357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369,
       370, 371, 372, 373, 374, 353, 375, 256, 350, 325, 326, 329, 330,
       331, 332, 334, 335, 336, 337, 338, 339, 340, 341, 343, 344, 345,
       346, 347, 348, 349, 351, 324, 376, 378, 407, 408, 409, 410, 412,
       413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425,
       426, 427, 428, 406, 377, 405, 403, 379, 380, 381, 382, 383, 384,
       385, 387, 388, 389, 390, 391, 392, 393, 394, 397, 398, 399, 400,
       401, 402, 404, 323, 352, 303, 296, 297, 298, 271, 299, 270, 269,
       272, 268, 302, 279, 304, 305, 306, 307, 308, 301, 309, 295, 293,
       278, 281, 282, 283, 284, 277, 285, 294, 286, 275, 274, 289, 290,
       291, 292, 273, 276, 310, 280, 266, 318, 317, 316, 263, 261, 315,
       314, 262, 260, 264, 320, 313, 259, 312, 258, 311, 319,  64, 333,
       158, 672, 598, 891, 104, 648, 749, 321, 241, 857,  48, 630, 715,
       896, 700, 106,  88,  39, 458, 485, 922, 693, 905, 669, 243, 465,
       599, 656, 117, 740, 932, 568, 522, 557, 174, 906, 300, 732, 386,
       456, 172, 322, 787, 725, 173, 265, 209,  86,  43, 528, 933, 729,
       525, 561, 760, 762,  40, 681, 288,  75, 685,  83,  91, 167,  33,
       502, 619, 867, 165, 267, 464, 759, 908, 503,  69, 430, 593, 626,
        78, 439, 858, 639, 810, 804, 587, 470, 623,  62, 780, 774, 719,
        41, 806, 328,  18, 327, 142, 826, 226, 100, 741, 411, 193,  15,
       915, 342,  23, 511, 396, 454, 768, 923, 395, 450, 435, 148, 814,
       758,  28, 588, 913, 451, 455, 565, 654,  11, 445, 113,   7, 457,
       657, 436,   3, 287, 764, 452,  27,  22, 448, 449, 440,   0])

In [29]:
np.argsort(score)[-5:]

array([ 22, 448, 449, 440,   0])

In [30]:
df.iloc[449].text

'Yes, you can. You won’t be able to submit some of the homeworks, but you can still take part in the course.\nIn order to get a certificate, you need to submit 2 out of 3 course projects and review 3 peers’ Projects by the deadline. It means that if you join the course at the end of November and manage to work on two projects, you will still be eligible for a certificate.'

In [31]:
# Let's now do it for all the documents:

fields = ['section', 'question', 'text']

In [32]:
matrices = {}
vectorizers = {}

for f in fields:
    tv = TfidfVectorizer(min_df=5, stop_words='english')
    X = tv.fit_transform(df[f])
    matrices[f] = X
    vectorizers[f] = tv

In [33]:
n = len(df)

In [34]:
# We can do it for all the fields. Let's also boost one of the fields - 
# question - to give it more importance than to others

score = np.zeros(n)
query = "I just discovered the course, is it too late to join?"

boosts = {
    'question': 3,
    # 'text': 0.5
}

for f in fields:
    q = vectorizers[f].transform([query])
    X = matrices[f]

    f_score = cosine_similarity(X, q).flatten()

    boost = boosts.get(f, 1.0)
    
    score = score + boost * f_score

In [35]:
filters = {
    'course': 'data-engineering-zoomcamp' 
}

In [36]:
for field, value in filters.items():
    mask = (df[field] == value).astype(int).values
    score = score * mask

In [37]:
idx = np.argsort(score)[-5:]

In [38]:
df.iloc[idx]

,course,section,question,text
4,data-engineering-zoomcamp,General course-related questions,Course - What can I do before the course starts?,You can start by installing and setting up all...
34,data-engineering-zoomcamp,General course-related questions,How can we contribute to the course?,Star the repo! Share it with friends if you fi...
1,data-engineering-zoomcamp,General course-related questions,Course - What are the prerequisites for this c...,GitHub - DataTalksClub data-engineering-zoomca...
0,data-engineering-zoomcamp,General course-related questions,Course - When will the course start?,The purpose of this document is to capture fre...
7,data-engineering-zoomcamp,General course-related questions,Course - Can I follow the course after it fini...,"Yes, we will keep all the materials after the ..."

In [39]:
class TextSearch:

    def __init__(self, text_fields):
        self.text_fields = text_fields
        self.matrices = {}
        self.vectorizers = {}

    def fit(self, records, vectorizer_params={}):
        self.df = pd.DataFrame(records)

        for f in self.text_fields:
            tv = TfidfVectorizer(**vectorizer_params)
            X = tv.fit_transform(self.df[f])
            self.matrices[f] = X
            self.vectorizers[f] = tv

    def search(self, query, n_results=10, boost={}, filters={}):
        score = np.zeros(len(self.df))

        for f in self.text_fields:
            b = boost.get(f, 1.0)
            q = self.vectorizers[f].transform([query])
            s = cosine_similarity(self.matrices[f], q).flatten()
            score = score + b * s

        for field, value in filters.items():
            mask = (self.df[field] == value).values
            score = score * mask

        idx = np.argsort(-score)[:n_results]
        results = self.df.iloc[idx]
        return results.to_dict(orient='records')

In [40]:
index = TextSearch(
    text_fields=['section', 'question', 'text']
)
index.fit(documents)

index.search(
    query='I just signed up. Is it too late to join the course?',
    n_results=5,
    boost={'question': 3.0},
    filters={'course': 'data-engineering-zoomcamp'}
)

[{'text': "Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute.",
  'section': 'General course-related questions',
  'question': 'Course - Can I still join the course after the start date?',
  'course': 'data-engineering-zoomcamp'},
 {'text': "The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.",
  'section': 'General course-related questions',
  'question': 'Course - When will the course start?',
  'course': 'data-engineering-zoomcamp'},
 {'text': 'Yes, we will keep all the materials after the course finishes, so you can follow the course at your own pace after it finishes.\nYou can also continue looking at the homeworks and continue preparing for the next cohort. I guess you can also start working on your final capstone project.',
  'section': 'General course-related questions',
  'question': 'Course - Can I follow the course after it finishes?',
  'course': 'data-engineering-zoomcamp'},
 {'text': 'No, late submissions are not allowed. But if the form is still not closed and it’s after the due date, you can still submit the homework. confirm your submission by the date-timestamp on the Course page.y\nOlder news:[source1] [source2]',
  'section': 'General course-related questions',
  'question': 'Homework - Are late submissions of homework allowed?',
  'course': 'data-engineering-zoomcamp'},
 {'text': 'You can start by installing and setting up all the dependencies and requirements:\nGoogle cloud account\nGoogle Cloud SDK\nPython 3 (installed with Anaconda)\nTerraform\nGit\nLook over the prerequisites and syllabus to see if you are comfortable with these subjects.',
  'section': 'General course-related questions',
  'question': 'Course - What can I do before the course starts?',
  'course': 'data-engineering-zoomcamp'}]

In [41]:
# Embeddings and Vector Search

# Problem with text - only exact matches. How about synonyms?

# What are Embeddings?

# Conversion to Numbers: Embeddings transform different words, sentences and documents into dense vectors 
# (arrays with numbers).
# Capturing Similarity: They ensure similar items have similar numerical vectors, illustrating their closeness 
# in terms of characteristics.
# Dimensionality Reduction: Embeddings reduce complex characteristics into vectors.
# Use in Machine Learning: These numerical vectors are used in machine learning models for tasks 
# such as recommendations, text analysis, and pattern recognition.


# SVD
# Singular Value Decomposition is the simplest way to turn Bag-of-Words representation into embeddings

# This way we still don't preserve the word order (because it wasn't in the Bag-of-Words representation) 
# but we reduce dimensionality and capture synonyms.

# We won't go into mathematics, it's sufficient to know that SVD "compresses" our input vectors in such a way 
# that as much as possible of the original information is retained.

# This compression is lossy compression - meaning that we won't be able to restore the 100% of the original vector,
# but the result is close enough.

# Let's use the vectorizer for the "text" field and turn it into embeddings

X = matrices['text']
cv = vectorizers['text']

In [42]:
svd = TruncatedSVD(n_components=16)
X_emb = svd.fit_transform(X)

In [43]:
X_emb[0] #this is called embedding

array([ 0.09653218, -0.08222545, -0.10191375, -0.07922607,  0.06688672,
       -0.06256561,  0.01418307, -0.14190464,  0.25960355,  0.28921267,
        0.05914533,  0.05009755, -0.11385946,  0.07231508,  0.01883043,
       -0.05239083])

In [44]:
query = 'I just signed up. Is it too late to join the course?'

Q = cv.transform([query])
Q_emb = svd.transform(Q)
Q_emb[0]

array([ 0.05790248, -0.03853619, -0.05645908, -0.02777182,  0.03868663,
       -0.06286076,  0.00500516, -0.09207058,  0.18043457,  0.18534738,
        0.04352085,  0.05246602, -0.07339404,  0.05655208,  0.03218051,
       -0.02572572])

In [45]:
# Similarity between query and the document:

np.dot(X_emb[0], Q_emb[0])

0.15641777163992066

In [46]:
score = cosine_similarity(X_emb, Q_emb).flatten()
idx = np.argsort(-score)[:10]
list(df.loc[idx].text)

['If you have submitted two projects (and peer-reviewed at least 3 course-mates’ projects for each submission), you will get the certificate for the course. According to the course coordinator, Alexey Grigorev, only two projects are needed to get the course certificate.\n(optional) David Odimegwu',
 "The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.",
 'Yes, you can. You won’t be able to submit some of the homeworks, but you can still take part in the course.\nIn order to get a certificate, you need to submit 2 out of 3 course projects and review 3 peers’ Projects by the deadline. It means that if you join the course at the end of November and manage to work on two projects, you will still be eligible for a certificate.',
 'The course videos are pre-recorded, you can start watching the course right now.\nWe will also occasionally have office hours - live sessions where we will answer your questions. The office hours sessions are recorded too.\nYou can see the office hours as well as the pre-recorded course videos in the course playlist on YouTube.',
 'Please choose the closest one to your answer. Also do not post your answer in the course slack channel.',
 'Yes! Every “Office Hours” will be recorded and available a few minutes after the live session is over; so you can view (or rewatch) whenever you want.',
 'Yes, we will keep all the materials after the course finishes, so you can follow the course at your own pace after it finishes.\nYou can also continue looking at the homeworks and continue preparing for the next cohort. I guess you can also start working on your final capstone project.',
 "Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute.",
 'No, it’s not possible. The form is closed after the due date. But don’t worry, homework is not mandatory for finishing the course.',
 'No, late submissions are not allowed. But if the form is still not closed and it’s after the due date, you can still submit the homework. confirm your submission by the date-timestamp on the Course page.y\nOlder news:[source1] [source2]']

In [47]:
# Non-Negative Matrix Factorization

# SVD creates values with negative numbers. It's difficult to interpet them.

# NMF (Non-Negative Matrix Factorization) is a similar concept, 
# except for non-negative input matrices it produces non-negative results.

# We can interpret each of the columns (features) of the embeddings as different topic/concepts 
# and to what extent this document is about this concept.

nmf = NMF(n_components=16)
X_emb = nmf.fit_transform(X)
X_emb[0]

array([0.12965297, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.00062601, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ])

In [48]:
Q = cv.transform([query])
Q_emb = nmf.transform(Q)
Q_emb[0]

array([0.08617097, 0.00241399, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.00249377,
       0.        ])

In [49]:
score = cosine_similarity(X_emb, Q_emb).flatten()
idx = np.argsort(-score)[:10]
df.loc[idx]

,course,section,question,text
2,data-engineering-zoomcamp,General course-related questions,Course - Can I still join the course after the...,"Yes, even if you don't register, you're still ..."
814,mlops-zoomcamp,+-General course questions,What if my answer is not exactly the same as t...,Please choose the closest one to your answer. ...
449,machine-learning-zoomcamp,General course-related questions,The course has already started. Can I still jo...,"Yes, you can. You won’t be able to submit some..."
11,data-engineering-zoomcamp,General course-related questions,Certificate - Can I follow the course in a sel...,"No, you can only get a certificate if you fini..."
0,data-engineering-zoomcamp,General course-related questions,Course - When will the course start?,The purpose of this document is to capture fre...
764,machine-learning-zoomcamp,Projects (Midterm and Capstone),What If I submitted only two projects and fail...,If you have submitted two projects (and peer-r...
7,data-engineering-zoomcamp,General course-related questions,Course - Can I follow the course after it fini...,"Yes, we will keep all the materials after the ..."
451,machine-learning-zoomcamp,General course-related questions,Can I submit the homework after the due date?,"No, it’s not possible. The form is closed afte..."
436,machine-learning-zoomcamp,General course-related questions,Is it going to be live? When?,"The course videos are pre-recorded, you can st..."
450,machine-learning-zoomcamp,General course-related questions,When does the next iteration start?,The course is available in the self-paced mode...

In [50]:
# BERT

# The problem with the previous two approaches is that they don't take into account the word order. 
# They just treat all the words separately (that's why it's called "Bag-of-Words")

# BERT and other transformer models don't have this problem.

# Let's create embeddings with BERT. We will use the Hugging Face library for that

# We need:
# tokenizer - for turning text into vectors
# model - for compressing the text into embeddings

import torch
from transformers import BertModel, BertTokenizer

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertModel.from_pretrained("bert-base-uncased")
model.eval()  # Set the model to evaluation mode if not training

/Users/romi9987/Documents/Python_Workspace/llm-course/venv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
          (intermediate_act_fn): GELUActivation()
        )
        (output): BertOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
  )
  (pooler): BertPooler(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (activation): Tanh()
  )
)

In [51]:
texts = [
    "Yes, we will keep all the materials after the course finishes.",
    "You can follow the course at your own pace after it finishes"
]
encoded_input = tokenizer(texts, padding=True, truncation=True, return_tensors='pt')

In [52]:
encoded_input

{'input_ids': tensor([[  101,  2748,  1010,  2057,  2097,  2562,  2035,  1996,  4475,  2044,
          1996,  2607, 12321,  1012,   102],
        [  101,  2017,  2064,  3582,  1996,  2607,  2012,  2115,  2219,  6393,
          2044,  2009, 12321,   102,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]])}

In [53]:
# Then we compute the embeddings:

with torch.no_grad():  # Disable gradient calculation for inference
    outputs = model(**encoded_input)
    hidden_states = outputs.last_hidden_state

In [55]:
hidden_states.shape

torch.Size([2, 15, 768])

In [56]:
# Now we need to compress the embeddings:

sentence_embeddings = hidden_states.mean(dim=1)
sentence_embeddings.shape

torch.Size([2, 768])

In [57]:
sentence_embeddings

tensor([[ 0.3600, -0.1607,  0.3545,  ...,  0.0429,  0.0348, -0.0382],
        [ 0.1785, -0.5000,  0.2528,  ..., -0.1141, -0.3361,  0.4110]])

In [58]:
# And convert them to a numpy array

X_emb = sentence_embeddings.numpy()

In [59]:
sentence_embeddings_cpu = sentence_embeddings.cpu()

In [60]:
# Let's now compute it for our texts. We'll do it in batches. First, we define a function for batching:

def make_batches(seq, n):
    result = []
    for i in range(0, len(seq), n):
        batch = seq[i:i+n]
        result.append(batch)
    return result

In [61]:
from tqdm.auto import tqdm
texts = df['text'].tolist()
text_batches = make_batches(texts, 8)

all_embeddings = []

for batch in tqdm(text_batches):
    encoded_input = tokenizer(batch, padding=True, truncation=True, return_tensors='pt')

    with torch.no_grad():
        outputs = model(**encoded_input)
        hidden_states = outputs.last_hidden_state
        
        batch_embeddings = hidden_states.mean(dim=1)
        batch_embeddings_np = batch_embeddings.cpu().numpy()
        all_embeddings.append(batch_embeddings_np)

final_embeddings = np.vstack(all_embeddings)

100%|████████████████████████████████████████████████████████████| 119/119 [03:58<00:00,  2.00s/it]

In [62]:
# Let's put it into a function:

def compute_embeddings(texts, batch_size=8):
    text_batches = make_batches(texts, 8)
    
    all_embeddings = []
    
    for batch in tqdm(text_batches):
        encoded_input = tokenizer(batch, padding=True, truncation=True, return_tensors='pt')
    
        with torch.no_grad():
            outputs = model(**encoded_input)
            hidden_states = outputs.last_hidden_state
            
            batch_embeddings = hidden_states.mean(dim=1)
            batch_embeddings_np = batch_embeddings.cpu().numpy()
            all_embeddings.append(batch_embeddings_np)
    
    final_embeddings = np.vstack(all_embeddings)
    return final_embeddings

In [63]:
X_text = compute_embeddings(df['text'].tolist())

100%|████████████████████████████████████████████████████████████| 119/119 [04:17<00:00,  2.16s/it]

In [64]:
X_text

array([[-0.00456306, -0.11667504,  0.62747175, ..., -0.03659184,
         0.10031681,  0.02927131],
       [-0.142336  , -0.19853921,  0.2845541 , ..., -0.01139036,
        -0.15399769,  0.09535078],
       [ 0.19672245, -0.084613  ,  0.28200504, ...,  0.11395874,
        -0.06448024, -0.01282621],
       ...,
       [-0.28217432, -0.3332435 ,  0.29785007, ..., -0.35042733,
         0.03266051,  0.09537253],
       [-0.42807105, -0.39468753,  0.30941987, ..., -0.05943286,
        -0.12965176,  0.07887052],
       [-0.16892132, -0.25146264,  0.47843295, ..., -0.18535407,
        -0.16108924,  0.27272928]], dtype=float32)